### ISSUE TITLE
Error while deploying custom AEM component

### ISSUE THREAD

**Issue by khushboo-agarwal14** [Adobe-Marketing-Cloud/aem-guides-wknd#53]
Hi,

 

I have built the custom AEM component 'Byline' by following AEM WKND tutorial. However, after deployment, I am not able to find my component model in AEM web console for Sling models. I am using AEM 6.4 quickstart, getting following errors while using this component:

 Caused by: org.apache.sling.scripting.sightly.SightlyException: Compilation errors in org/apache/sling/scripting/sightly/apps/wknd/components/content/byline/byline_html.java:
**Line 28, column 1272 : Only a type can be imported. com.adobe.aem.guides.wknd.core.components.Byline resolves to a package**
Line 49, column 2354 : Byline cannot be resolved to a type
at org.apache.sling.scripting.sightly.impl.engine.SightlyJavaCompilerService.compileSource(S ightlyJavaCompilerService.java:173) [org.apache.sling.scripting.sightly:1.0.48.1_3_1]
    ... 286 common frames omitted

Unable to resolve com.adobe.aem.guides.wknd.core [551](R 551.19): missing requirement [com.adobe.aem.guides.wknd.core [551](R 551.19)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models)(version>=12.5.0)(!(versio n>=13.0.0))) **Unresolved requirements: [[com.adobe.aem.guides.wknd.core [551](R 551.19)] osgi.wiring.package; (&(osgi.wiring.package=com.adobe.cq.wcm.core.components.models)**(version>=12.5.0)(!(versio n>=13.0.0)))]
at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:9 7) [org.apache.sling.installer.core:3.8.12]
at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.j ava:902) [org.apache.sling.installer.core:3.8.12]
at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.jav a:737) [org.apache.sling.installer.core:3.8.12]
at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:287) [org.apache.sling.installer.core:3.8.12]
at java.lang.Thread.run(Thread.java:748)

Also, I can see following error while viewing my site OSGi bundle in AEM Web console:
**com.adobe.cq.wcm.core.components.models,version=[12.5,13) -- Cannot be resolved**

Am I missing any configuration or mvn dependency? Can I please get some help to resolve these errors?

**Comment by godanny86** [comment]
hi @khushboo-agarwal14, what version of Core Components is installed? The tutorial was recently updated to use 2.2.0 which requires AEM 6.4 + SP2...

**Comment by khushboo-agarwal14** [comment]
Hi Daniel,

Thanks for replying. I was using 2.0.4 for core components. I have updated it to use 2.2.0 which seems to have fixed the errors. Thank you very much for your help in resolving these errors. 

Best regards,
Khushboo
